version: '3'
services:
  app:
    build: .
    ports:
      - '3005:3005'
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    command: --quiet
